### PR TITLE
Use extend instead of copy

### PR DESCRIPTION
**Pull request by ynicolaou**
angular.copy is significantly slower than angular.extend in 1.3. This can cause slowness, and i couldn't find a reason why we should be deep copying models.

### CODE REVIEW

**Comment by ynicolaou** [comment]
@natevecc do you recall why you used copy in the first place?

**Comment by bengarvey** [comment]
@ynicolaou as we discussed, try to take the copy out and see if it works.

**Comment by natevecc** [comment]
@bengarvey @ynicolaou Hey guys sorry I didn't respond to this sooner. Broke my ankle this past week.

Anyway you have to use angular.copy because angular.copy does a deep copy of all properties and nested objects/arrays while extend only does a shallow copy. This is important because of how the model cache works. The copy is used to guarantee the object in the cache can only be accessed through the ModelFactory API. If you have any other questions let me know.

**Comment by ynicolaou** [comment]
@natevecc i'm not sure i understand what you mean by ```guarantee the object in the cache can only be accessed through the ModelFactory API```. If i have a model i just retrieved from the the model-factory, what prevents me from modifying that model by doing something like ```model.data.row = 10```. When i modify the model that way, it will go all the way back to the cache. Don't i essentially bypass the API when i do that?

Also when i looked at the code where ```angular.copy``` is used, i couldn't find a code path towards it that doesn't originate from a success response. Why should we care about mutating response data?

**Comment by natevecc** [comment]
@ynicolaou I guess I was worried about the data leaking out and thinking the dev was updating a model in the cache when they were not. I can't think of a good example but just be careful. Also the angular-resource code does an extend like thing: https://github.com/angular/angular.js/blob/master/src/ngResource/resource.js#L30

I'll merge it in.

**Comment by natevecc** [comment]
Err I can't merge only you guys can. Approved then!

**Comment by bengarvey** [comment]
@natevecc that sucks about your ankle. 

@ynicolaou This is approved, but I'm posting some of our slack chat here for future debuggers in case a bug arises from this change

bengarvey [9:52 AM] 
@ynicolaou: yeah, did you try it without the extend?

ynicolaou [9:54 AM] 
we need an extend there because we are taking the properties of the data response and assigning them to the model (this).

bengarvey [9:58 AM] 
ok, so the thought here is that we have object A which came from the server. We extend A into object B, which copies all the properties (and anything 2 levels deep is a reference).  We can then use object B to do whatever we want and it will be fine.

ynicolaou [9:58 AM] 
yea

bengarvey [9:59 AM] 
My only question then is what happens to A? Does it just hang out somewhere?  Get destroyed? Get overwritten when we call .get again?

bengarvey [9:59 AM]
Is it possible to mutate those deep references later that will cause an issue with B

ynicolaou [10:02 AM] 
its possible to somehow mutate those references, but only if you do something to the response after you receive it and extend it onto A. But i don't think its possible to do that outside the model-factory.

ynicolaou [10:03 AM]
the model-factory is the one that makes the request and then assigns the response to A

ynicolaou [10:03 AM]
also as nate mentioned angular's resource also does an extend

**Pull request merged**
